name: track_bundle_size_comment_pr

on:
    workflow_run:
        workflows: ["track_bundle_size"]
        types:
            - completed

permissions:
    pull-requests: write

jobs:
    track_bundle_size_comment_pr:
        runs-on: ubuntu-latest
        if: >
            github.event.workflow_run.event == 'pull_request'
        steps:
            - uses: actions/github-script@v7
              with:
                script: |
                    console.log(JSON.stringify(context));
            - id: 'readPrArtifact'
              uses: './.github/actions/read-pr-artifact'
              with:
                  name: 'trackBundleSize.md'
                  workflow_run_id: ${{ github.event.workflow_run.id }}
            - name: 'Replace PR comment'
              uses: './.github/actions/replace-pr-comment'
              with:
                  pr_number: ${{ steps.readPrArtifact.outputs.pr_number }}
                  comment_content: ${{ steps.readPrArtifact.outputs.content }}
                  comment_author_equals: 'github-actions[bot]'
                  comment_body_includes: 'Generated by: track-bundle-size'
